TestUAEnergy/urls.py
from django.contrib import admin
from django.urls import path, include
from .proj_views import SetLangView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls', namespace='authorization')),
    path('csv/', include('csv_worker.urls', namespace='csv_worker')),
    path('set_language/<str:lang>/', SetLangView.as_view(), name='set_language')
]

authorization/urls.py
from django.urls import path
from . import views

app_name = 'authorization'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.Login.as_view(), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

csv_worker/urls.py
from django.urls import path
from . import views

app_name = 'csv_worker'

urlpatterns = [
    path('', views.CSVLoadView.as_view(), name='home'),
    path('view/', views.ShowTablesView.as_view(), name='view_csv'),
]

authorization/models.py
from django.db import models

# Create your models here.

csv_worker/models.py
from django.db import models

# Create your models here.

authorization/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.forms import ValidationError
from django.utils.translation import gettext as _


class UserEnergyForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise ValidationError(_("Access denied"))
        if user.username != 'uaenergy':
            raise ValidationError(_("You can't login with this account."))

csv_worker/forms.py
from django.forms import Form, FileField
from .validators import check_type_file, check_size_file
from django.utils.translation import gettext_lazy as _


class InputCSV(Form):
    required_css_class = 'form-control-file form-control-lg'

    file = FileField(label=_("Upload CSV file here..."), validators=[check_type_file, check_size_file])

authorization/views.py
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import UserEnergyForm

# Create your views here.


class HomeView(TemplateView):
    template_name = 'base.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('csv_worker:home')
        return super().dispatch(request, *args, **kwargs)


class Login(LoginView):
    template_name = "auth/login.html"
    authentication_form = UserEnergyForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('csv_worker:home')
        return super().dispatch(request, *args, **kwargs)


class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('authorization:login')
    template_name = 'auth/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('csv_worker:home')
        return super().dispatch(request, *args, **kwargs)


class LogOut(LogoutView):
    pass

csv_worker/views.py
from django.shortcuts import redirect
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView

from django.utils.translation import gettext as _

from .forms import InputCSV
from . import dbhelper
import json
from io import StringIO
import random
import collections
import csv

# Create your views here.


class CSVLoadView(FormView):
    template_name = 'csv_worker/load_csv.html'
    form_class = InputCSV

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('authorization:login')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        file = self.request.FILES['file']
        csv_raw = StringIO(file.read().decode("utf-8"))

        reader = csv.DictReader(csv_raw)

        result_dict = {}
        for row in reader:
            name_var = row.popitem(last=False)[1]
            result_dict[name_var] = json.dumps(row)

        dbhelper.create_table_with_data(**result_dict)
        return redirect('csv_worker:view_csv')


class ShowTablesView(TemplateView):
    template_name = 'csv_worker/tables.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('authorization:login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            for index, (name, data) in enumerate(dbhelper.get_data().items(), 1):
                context[f'table{index}_name'] = name
                context[f'table{index}_data'] = data
        except dbhelper.TableDoesNotExists:
            context['table_does_not_exists'] = _('No one CSV file loaded before...')

        context['table3_name'] = _('Random unique symbols')
        unique_symbols = list(map(chr, random.sample(range(0xd7ff), 16)))  # to 0x10ffff, if needed
        context['table3_data'] = collections.OrderedDict(
            [(f'Sym {index}', value) for index, value in zip(range(1, 17), unique_symbols)]
        )
        return context

csv_worker/templates/csv_worker/load_csv.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Hello' %}, {{ user.username }}!</h1>
    <form enctype="multipart/form-data" method="post" action="" lang="en">
        {% csrf_token %}

        <div class="form-group text-center">
            <label for="exampleFormControlFile1">{{ form.label }}</label>
            {{ form }}
        </div>

        <div class="form-group row">
            <div class="col-6 offset-3 text-center">
                <button type="submit" class="btn btn-primary">{% trans 'Upload' %}</button>
            </div>
        </div>
    </form>
    <div class="text-right">
        <a href={% url 'csv_worker:view_csv' %}>{% trans 'Or go to tables...' %}</a>
    </div>

{% endblock %}

csv_worker/templates/csv_worker/tables.html
{% extends 'base.html' %}
{% load filters_for_tables %}
{% load i18n %}

{% block content %}
    <h1 class="text-center">{% trans 'Tables' %}</h1>

    {% if table_does_not_exists %}
        <h4 class="text-center">{{ table_does_not_exists }}</h4>
    {% else %}
        <h5>{% trans 'Table for variable' %} '{{ table1_name }}':</h5>
        <table class="table table-bordered table-success">
            <thead>
                <tr>
                    {% for elem in table1_data %}
                        <th>{{ elem }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for value in table1_data.values %}
                        <td>{{ value|zeros_to_nines }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>

        <h5>{% trans 'Table for variable' %} '{{ table2_name }}':</h5>
        <table class="table table-bordered table-warning">
            <thead>
                <tr>
                    {% for elem in table2_data %}
                        <th>{{ elem }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for value in table2_data.values %}
                        <td>{{ value|only_latin_symbols }}</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    {% endif %}

    <h5>{% trans 'Table with' %} {{ table3_name|lower }}:</h5>
    <table class="table table-bordered table-danger table-striped">
        <thead>
            <tr>
                {% for elem in table3_data %}
                    <th>{{ elem }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            <tr>
                {% for value in table3_data.values %}
                    <td>{{ value }}</td>
                {% endfor %}
            </tr>
        </tbody>
    </table>

    <div class="text-right">
        <a href={% url 'csv_worker:home' %}>{% trans 'Go back...' %}</a>
    </div>
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UAEnergy</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" href=
                {% if user.is_authenticated %}{% url 'csv_worker:home' %}{% else %}
                    {% url 'authorization:home' %}{% endif %}>
            {% trans 'My Site :)' %} </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {% trans 'Language' %} ({{ LANGUAGE_CODE }})
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href={% url 'set_language' lang='en' %}>
                            {% language 'en' %}{% trans 'English' %}{% endlanguage %}</a>
                        <a class="dropdown-item" href={% url 'set_language' lang='ru' %}>
                            {% language 'ru' %}{% trans 'Russian' %}{% endlanguage %}</a>
                        <a class="dropdown-item" href={% url 'set_language' lang='uk' %}>
                            {% language 'uk' %}{% trans 'Ukrainian' %}{% endlanguage %}</a>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'authorization:signup' %}>{% trans 'Sign Up' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'authorization:login' %}>{% trans 'Login' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'authorization:logout' %}>{% trans 'Logout' %}
                            ({{ user.username }})</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}
            <p class="lead">{% trans 'Welcome! Please Login or Signup to continue...' %}</p>
        {% endblock %}
    </div>

    <footer class="footer">
        <div class="container text-center">
            <span>{% trans 'Created by Lysenko Vitaliy. (2019)' %}</span>
        </div>
    </footer>

    {% block script %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>
</html>